# Generated by Django 3.2.13 on 2022-11-23 06:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_like_users',
            field=models.ManyToManyField(blank=True, related_name='user_like_comment', to=settings.AUTH_USER_MODEL),
        ),
    ]
