# Generated by Django 3.2.13 on 2022-11-19 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
        ('accounts', '0002_auto_20221118_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='comment_like',
            field=models.ManyToManyField(related_name='user_comment', to='movies.Comment'),
        ),
        migrations.AddField(
            model_name='user',
            name='genre_like',
            field=models.ManyToManyField(related_name='user_genre', to='movies.Genre'),
        ),
    ]
